### ISSUE TITLE
some questions about adding my own esp (personal use)

### ISSUE THREAD

**Issue by Jolteon1234amongus** [ic3w0lf22/Unnamed-ESP#30]
I looked around in the script and I couldn't find what I was lookin for so yeah. How do I adjust line thickness and line transparency while using "CustomESP" as well as text outlines without changing the normal player esp settings? I also want to specify to use a box like how the normal esp works and make the studs away counter not below all the custom name and instead where ever I'd like.

what I did below idk how to make it use options and stuff

CustomESP = function()
  for i, v in pairs(game.Workspace.Live:GetChildren()) do
    if not game.Players:FindFirstChild(v.Name) then
      local head = v:FindFirstChild("Head")
      local hum = v:FindFirstChildOfClass("Humanoid")

       if head and hum then
        pcall(RenderList.AddOrUpdateInstance, RenderList, v, head, v.Name.."\n["..hum.Health.."/"..hum.MaxHealth.."]", Color3.fromRGB(7, 43, 244));
       end
     end
   end
end

**Comment by ic3w0lf22** [comment]
I don't recommend using this as a custom ESP because it's 
- Not documented
- Badly made/optimized
- Not very customizable 

What I do recommend though is [kiriot's ESP library](https://kiriot22.com/releases/ESP.lua) since its a lot easier
to use and also uses the drawing API. Not sure where you can find the documentation though.
